ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "saweriaUrl" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "qrisUrl" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "gopayNumber" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "bankAccount" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
